from . import flt_expiry_reminder_mixin
from . import res_partner
from . import flt_airline
from . import flt_airport
from . import flt_passport
from . import flt_visa
from . import flt_flight_booking
from . import flt_flight_segment
from . import flt_cancellation_policy
from . import flt_cancellation_request
from . import flt_document
from . import flt_notification
from . import flt_dashboard
from . import res_config_settings
